### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by apple502j** [vgno/koa-remove-trailing-slashes#6]
This package has security issues, which was privately reported to Snyk.

For repo owners: please contact me (or the Snyk team) for coordinated fix and disclosure. PGP key: https://apple502j.github.io/pubkey.txt

For users: please avoid using the package.

**Comment by kozmic** [comment]
@apple502j Thanks for reporting this to us! We have published version 2.0.2 to npmjs.com with a patch for the reported issue. We will push the commits, unit tests to reproduce it and more details on Monday.

**Comment by lirantal** [comment]
@kozmic since the fix is now anyway public as part of a new version on npm, is there a reason you didn't publish the fix here in source code?

**Comment by kozmic** [comment]
@lirantal We wanted to reach out to some third parties that are vulnerable before we released the unit tests (which basically are exploits). It's not very obvious from the patch how it can be exploited.

**Comment by lirantal** [comment]
Thanks, completely understood.
I was alert more on the side of perhaps some folks could see the disconnect from the npm version to the source control as a malicious version attempt.

**Comment by PAkerstrand** [comment]
@lirantal @kozmic Closed in 2500e4232ee8e5746ad0e8d1e83a9af22acd7d30. [Compare v2.0.1 to v2.0.2](https://github.com/vgno/koa-remove-trailing-slashes/compare/b7da3627d..2500e423).
Thanks a bunch @apple502j for reaching out to us.

Initial release notes are available here: https://github.com/vgno/koa-remove-trailing-slashes/releases/tag/v2.0.2

We will refine them as the CVE is finalized.

I also [published version 2.0.3](https://github.com/vgno/koa-remove-trailing-slashes/compare/v2.0.2..v2.0.3) today, since my fix accidentally broke compatibility with Node < v10. The latest patch release restores compatibility with Node v7. Release notes available here: https://github.com/vgno/koa-remove-trailing-slashes/releases/tag/v2.0.3

**Comment by lirantal** [comment]
Great job folks!
